[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v
markers =
    scenario_1: Testy dla scenariusza 1 - obszar logowania
    scenario_2: Testy dla scenariusza 2 - obszar przeglądania produktów
    scenario_3: Testy dla scenariusza 3 - obszar zarządzania koszykiem
    scenario_4: Testy dla scenariusza 4 - obszar realizacji zamówienia
    tc01: Przypadek testowy 01
    tc02: Przypadek testowy 02
    tc03: Przypadek testowy 03
    tc04: Przypadek testowy 04
    tc05: Przypadek testowy 05